@url = http://localhost:8086/order
### Get all
GET {{url}}/
### Get by id
GET {{url}}/3
### Create
POST {{url}}/
Content-Type: application/json

{
  "quantity" : 5,
  "amount" : 350000,
  "productId" : 2,
  "mode" : "CASH"
}

### Update
PUT {{url}}/3
Content-Type: application/json

{
  "quantity" : 2,
  "amount" : 3,
  "statusId" : 2
}

### Delete
DELETE  {{url}}/1
### Get Amount
GET {{url}}/1/amount